### ISSUE TITLE
Uploading threat model file produces a 500

### ISSUE THREAD

**Issue by mtesauro** [DefectDojo/django-DefectDojo#2835]
**Bug description**

When the "Upload Threat Model" link under an engagement and selecting a PDF file to upload, DefectDojo produces a 500 error when a directory named "threat" doesn't exit within the DefectDojo media directory (per settings.py).  Since DefectDojo can already write to that directory, it should check for the presence of the "threat" sub-directory and create it if it doesn't exits before trying to write the uploaded file to disk.

**_Workaround:_** Manually create a directory called "threat" inside the DefectDojo media directory before uploading any threat model files.

**Steps to reproduce**
Utilizing the "Upload Threat Model" link under an engagement 
![tm-01](https://user-images.githubusercontent.com/3422419/92140375-9d88e480-edd6-11ea-8203-60f091d3f21e.png)

and selecting a PDF file to upload, 

![tm-02](https://user-images.githubusercontent.com/3422419/92140710-138d4b80-edd7-11ea-941d-0b97fed0cfb4.png)

DefectDojo produces a 500 error.  

Looking at the logs
```
[pid: 19|app: 0|req: 77/120] 1.1.1.1 () {52 vars in 921 bytes} [Sat Aug 22 00:10:17 2020] GET /login?next=/alerts/count => generated 12074 bytes in 14 msecs (HTTP/1.1 200) 9 headers in 472 bytes (1 switches on core 0)
Internal Server Error: /engagement/1/threatmodel/upload
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.6/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/local/lib/python3.6/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python3.6/site-packages/django/contrib/auth/decorators.py", line 21, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "./dojo/engagement/views.py", line 1075, in upload_threatmodel
    handle_uploaded_threat(request.FILES['file'], eng)
  File "./dojo/utils.py", line 1190, in handle_uploaded_threat
    'wb+') as destination:
FileNotFoundError: [Errno 2] No such file or directory: '/app/media/threat/1.pdf'
```
The error is caused by the lack of a "threat' directory exiting in DefectDojo's media directory.

I corrected for the 500 by exec'ing into the dojo_uwsgi_1 container and manually creating the missing directory:

```
host.com $ docker exec -it dojo_uwsgi_1 sh
$ mkdir /app/media/threat
$ exit
```

**Expected behavior**

When uploading the first threat model, I'd expect DefectDojo to create the needed "threat" sub-directory in DefectDojo's media directory.

**Deployment method** *(select with an `X`)*
- [ ] Kubernetes
- [X] Docker 
- [ ] setup.bash / legacy-setup.bash

**Environment information**
Ubuntu 20.04 host OS using docker compose and upstream 1.7.1 images from Docker Hub:

```
# docker-compose --version
docker-compose version 1.25.5, build 8a1c60f6
# docker --version
Docker version 19.03.12, build 48a66213fe
# cat docker-compose.yml | grep sha256 | uniq
    image: defectdojo/defectdojo-nginx:1.7.1@sha256:fa81e43e4e1fac2daf087cdc1c68cc492fffc67ee0249b0b15a7957c51866e44
    image: defectdojo/defectdojo-django:1.7.1@sha256:9fe0c03bfff843ae0a825548c3b3e015bad7b40f0e44133ae60e0373c5d64e35
    image: mysql:5.7.31@sha256:d3418a353847c7b34e3b082d1ea35a9d12fd1244d3d841d8cfe076e72c216b00
    image: rabbitmq:3.8.7-alpine@sha256:2cb78a0a8312e1eadb54321674043b9c893e1b2c90e5062a5089bb9fe0c45f32
```

**Sample scan files** (optional)
N/A

**Screenshots** (optional)
Attached above

**Console logs** (optional)
Provided above

**Additional context** (optional)
None.

**Comment by nagy3n** [comment]
Can you assign this to me?

**Comment by nagy3n** [comment]
This should fix it but I'm not sure if it's the best approach 
```diff
+def create_folder_if_not_exist(path):
+    if not os.path.isdir(path):
+        os.mkdir(path)


def handle_uploaded_threat(f, eng):
    name, extension = os.path.splitext(f.name)
+    create_folder_if_not_exist(settings.MEDIA_ROOT + '/threat')
```
Maybe if this fix is included inside a common bash script that gets runned in all django entrypoint scripts that does the same thing

**Comment by XiChen-Tibco** [comment]
Hey @mtesauro , for some reason we cannot reproduce the error, would you mind give us more information?

Thanks.

**Comment by mtesauro** [comment]
The 500 was caused when using docker containers via docker-compose to run DefectDojo which included a bind-mount for the media directory.

If there wasn't a "threat" sub-directory present in the media directory AND you tried to upload a threat model, you would get a 500 from DefectDojo.

However, I think @Maffooch corrected for this a while ago when he did a PR to improve file uploads generally in DefectDojo.

**Comment by mtesauro** [comment]
Just tried this on the demo server and DefectDojo will still throw a 500.

Steps I took to reproduce:

One the demo server, renamed the /opt/dojo/media/threat directory:

`
cd /opt/dojo/media/threat
mv threat not-threat
`
In a browser:

Re-follow the steps noted above to upload the PDF below:
[threat-model.pdf](https://github.com/DefectDojo/django-DefectDojo/files/6832003/threat-model.pdf)

Uploading the PDF:
![image](https://user-images.githubusercontent.com/3422419/125978079-cc6bd92e-1a75-4aba-a8d6-30e63ce674bb.png)

Got a 500 from DefectDojo:
![image](https://user-images.githubusercontent.com/3422419/125978153-46e33abf-5b8f-4c95-87f5-f3572708b3e0.png)

I've left the directory in the re-named state on the demo server in case you want to replicate what I did above ^

**Comment by mtesauro** [comment]
@XiChen-Tibco I'm going to revert the name change of the threats directory. Ping me if you need me to "break" the demo again for you to test a fix for this issue.

**Comment by XiChen-Tibco** [comment]
@Maffooch Can you assign this for me, finally I can re-produce this error and the Assignees for this issue is still empty.
