### ISSUE TITLE
Gitleaks parser fails on smileys in report

### ISSUE THREAD

**Issue by true-hero** [DefectDojo/django-DefectDojo#4336]
## Bug description
DD parser (in my case gitleaks parser), fails with 500 error code, when there is smile in string. 

## Steps to reproduce
1. Get gitleaks report 
2. Add some smile in report (or smiles can already be in report)
3. Try to import the report

## Expected behavior
Smiles have to be escaped.

## Environment information
 - DefectDojo 1.14.1

## Sample scan files
```json
[
 {
  "line": "\u003e [First you 😂😂then you 😢](https://twitter.com/kramse/status/1073168529405472768)",
  "lineNumber": 23,
  "offender": "twitter.com/kramse/status/1073168529405472768",
  "commit": "",
  "repo": "",
  "repoURL": "",
  "leakURL": "",
  "rule": "Twitter Client ID",
  "commitMessage": "",
  "author": "",
  "email": "",
  "file": "README.md",
  "date": "0001-01-01T00:00:00Z",
  "tags": "client, Twitter"
 }
]
```

## Logs
```
uwsgi_1         | [22/Apr/2021 11:28:46] DEBUG [dojo.importers.importer.importer:61] starting import of 1 items.
uwsgi_1         | [22/Apr/2021 11:28:46] DEBUG [dojo.finding.helper:48] changed fields: {'id': (None, None)}
uwsgi_1         | [22/Apr/2021 11:28:46] DEBUG [dojo.models:2186] Saving finding of id None dedupe_option:False (self.pk is None)
uwsgi_1         | [22/Apr/2021 11:28:46] ERROR [dojo.engagement.views:614] (1366, "Incorrect string value: '\\xF0\\x9F\\x98\\x82\\xF0\\x9F...' for column 'description' at row 1")
uwsgi_1         | Traceback (most recent call last):
uwsgi_1         |   File "/usr/local/lib/python3.6/site-packages/django/db/backends/utils.py", line 84, in _execute
uwsgi_1         |     return self.cursor.execute(sql, params)
uwsgi_1         |   File "/usr/local/lib/python3.6/site-packages/django/db/backends/mysql/base.py", line 71, in execute
uwsgi_1         |     return self.cursor.execute(query, args)
uwsgi_1         |   File "/usr/local/lib/python3.6/site-packages/MySQLdb/cursors.py", line 206, in execute
uwsgi_1         |     res = self._query(query)
uwsgi_1         |   File "/usr/local/lib/python3.6/site-packages/MySQLdb/cursors.py", line 319, in _query
uwsgi_1         |     db.query(q)
uwsgi_1         |   File "/usr/local/lib/python3.6/site-packages/MySQLdb/connections.py", line 259, in query
uwsgi_1         |     _mysql.connection.query(self, query)
uwsgi_1         | MySQLdb._exceptions.OperationalError: (1366, "Incorrect string value: '\\xF0\\x9F\\x98\\x82\\xF0\\x9F...' for column 'description' at row 1")
uwsgi_1         | 
uwsgi_1         | The above exception was the direct cause of the following exception:
uwsgi_1         | 
uwsgi_1         | Traceback (most recent call last):
uwsgi_1         |   File "./dojo/engagement/views.py", line 602, in import_scan_results
uwsgi_1         |     close_old_findings=close_old_findings)
uwsgi_1         |   File "./dojo/importers/importer/importer.py", line 253, in import_scan
uwsgi_1         |     now=now)
uwsgi_1         |   File "./dojo/importers/importer/importer.py", line 88, in process_parsed_findings
uwsgi_1         |     item.save(dedupe_option=False)
uwsgi_1         |   File "./dojo/models.py", line 2187, in save
uwsgi_1         |     super(Finding, self).save(*args, **kwargs)
uwsgi_1         |   File "/usr/local/lib/python3.6/site-packages/django/db/models/base.py", line 744, in save
uwsgi_1         |     force_update=force_update, update_fields=update_fields)
uwsgi_1         |   File "/usr/local/lib/python3.6/site-packages/django/db/models/base.py", line 782, in save_base
uwsgi_1         |     force_update, using, update_fields,
uwsgi_1         |   File "/usr/local/lib/python3.6/site-packages/django/db/models/base.py", line 873, in _save_table
uwsgi_1         |     result = self._do_insert(cls._base_manager, using, fields, update_pk, raw)
uwsgi_1         |   File "/usr/local/lib/python3.6/site-packages/django/db/models/base.py", line 911, in _do_insert
uwsgi_1         |     using=using, raw=raw)
uwsgi_1         |   File "/usr/local/lib/python3.6/site-packages/django/db/models/manager.py", line 82, in manager_method
uwsgi_1         |     return getattr(self.get_queryset(), name)(*args, **kwargs)
uwsgi_1         |   File "/usr/local/lib/python3.6/site-packages/django/db/models/query.py", line 1186, in _insert
uwsgi_1         |     return query.get_compiler(using=using).execute_sql(return_id)
uwsgi_1         |   File "/usr/local/lib/python3.6/site-packages/django/db/models/sql/compiler.py", line 1377, in execute_sql
uwsgi_1         |     cursor.execute(sql, params)
uwsgi_1         |   File "/usr/local/lib/python3.6/site-packages/django/db/backends/utils.py", line 99, in execute
uwsgi_1         |     return super().execute(sql, params)
uwsgi_1         |   File "/usr/local/lib/python3.6/site-packages/django/db/backends/utils.py", line 67, in execute
uwsgi_1         |     return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
uwsgi_1         |   File "/usr/local/lib/python3.6/site-packages/django/db/backends/utils.py", line 76, in _execute_with_wrappers
uwsgi_1         |     return executor(sql, params, many, context)
uwsgi_1         |   File "/usr/local/lib/python3.6/site-packages/django/db/backends/utils.py", line 84, in _execute
uwsgi_1         |     return self.cursor.execute(sql, params)
uwsgi_1         |   File "/usr/local/lib/python3.6/site-packages/django/db/utils.py", line 89, in __exit__
uwsgi_1         |     raise dj_exc_value.with_traceback(traceback) from exc_value
uwsgi_1         |   File "/usr/local/lib/python3.6/site-packages/django/db/backends/utils.py", line 84, in _execute
uwsgi_1         |     return self.cursor.execute(sql, params)
uwsgi_1         |   File "/usr/local/lib/python3.6/site-packages/django/db/backends/mysql/base.py", line 71, in execute
uwsgi_1         |     return self.cursor.execute(query, args)
uwsgi_1         |   File "/usr/local/lib/python3.6/site-packages/MySQLdb/cursors.py", line 206, in execute
uwsgi_1         |     res = self._query(query)
uwsgi_1         |   File "/usr/local/lib/python3.6/site-packages/MySQLdb/cursors.py", line 319, in _query
uwsgi_1         |     db.query(q)
uwsgi_1         |   File "/usr/local/lib/python3.6/site-packages/MySQLdb/connections.py", line 259, in query
uwsgi_1         |     _mysql.connection.query(self, query)
uwsgi_1         | django.db.utils.OperationalError: (1366, "Incorrect string value: '\\xF0\\x9F\\x98\\x82\\xF0\\x9F...' for column 'description' at row 1")
```

**Comment by damiencarol** [comment]
taking this one.

**Comment by damiencarol** [comment]
@true-hero I need more details. It depends also on how the database is configured

**Comment by true-hero** [comment]
@damiencarol, my database is fully configured with DD migrations. I only install MySQL as Linux service. As i understand, i have the utf8mb4_0900_ai_ci encoding of dojo_finding.description. 
![image](https://user-images.githubusercontent.com/32260664/115860955-e3b0b800-a43a-11eb-8e9b-17aa15db3a43.png)

**Comment by damiencarol** [comment]
the things is I think a modification in settings.py is required to "force" the software to use UTF8.
take a look at the link I pushed.
```

5

The problem appears to be in the Client.

When the client connects to the MySQL server, it needs to announce that the bytes in the client are utf8mb4. This can be done in several ways:

    In the connection parameters (client-dependent).
    SET NAMES utf8mb4.

\U+1F600 is the Unicode representation for that Emoji.
\xF0\x9F\x98\x80 is the equivalent Hex.
F09F9880 is the UTF-8 (utf8mb4) in Hex.

Avoid the Unicode representation.

```
For us it means adding options in DATABASES['default']['OPTIONS']

**Comment by true-hero** [comment]
It should look something like this?
```python
DATABASES['default']['OPTIONS']['charset'] = 'utf8'
```
Is it ok to use it in local_settings.py?

**Comment by damiencarol** [comment]
better to use `local_settings.py`.
I don't know the exact parameter name.

**Comment by damiencarol** [comment]
@true-hero any news from this issue? Did you found the good parameters?

**Comment by true-hero** [comment]
@damiencarol , as i remember, it was something like this:
`DATABASES['default']['OPTIONS']['charset'] = 'utf8'`
I face the problem on testing environment and solve the problem by deleting smiles from report.
But problem still exists:
![Снимок экрана 2021-08-10 в 11 09 03](https://user-images.githubusercontent.com/32260664/128831760-a533d248-a35d-4ee7-8541-c20dbd3d8097.png)
![Снимок экрана 2021-08-10 в 11 09 49](https://user-images.githubusercontent.com/32260664/128831859-047f341d-9081-4d22-a968-587f1cce3b83.png)
I have planned to bring charset variable to production when I update to new release.

**Comment by damiencarol** [comment]
@true-hero I was able to reproduce the pb. It's not a bug.

1. First take a look at my PR #4996 that improve Gitleaks parser and add more unit tests with your file is integrated.

2. I used a connection string in this form to force the client Python code to specify encoding:
`mysql://defectdojo:defectdojo@mysql:3306/defectdojo?charset=utf8mb4`

It solved the configuration pb for me:
![image](https://user-images.githubusercontent.com/1694940/131326238-600a5495-bc86-4de0-b067-da9ee42eb49d.png)

**Comment by damiencarol** [comment]
More context/details about this subject: https://adamhooper.medium.com/in-mysql-never-use-utf8-use-utf8mb4-11761243e434

@true-hero what is the status of this issue?

**Comment by true-hero** [comment]
Hello @damiencarol , thx for response. I did not face the problem anymore, it is rare issue. I reproduced it now, and this `?charset=utf8mb4` is the fix.
<img width="968" alt="Снимок экрана 2022-01-14 в 17 01 59" src="https://user-images.githubusercontent.com/32260664/149527612-fec8a2dc-cc98-4260-b9c1-713b0cc2a9bf.png">
